module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-License-Key');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { configType, domain, options = {} } = req.body;

    if (!configType || !domain) {
      return res.status(400).json({ error: 'configType and domain are required' });
    }

    const config = generateNginxConfig(configType, domain, options);

    return res.status(200).json({
      success: true,
      config: config,
      configType: configType,
      domain: domain
    });
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
};

function generateNginxConfig(type, domain, options) {
  const upstream = options.upstream || 'localhost:3000';
  const ssl = options.ssl !== false;
  const rateLimit = options.rateLimit || false;
  const gzip = options.gzip !== false;
  const caching = options.caching || false;

  let config = `# Nginx Configuration for ${domain}
# Generated by Nginx Config Generator Pro
# Type: ${type}
\n`;

  // Rate limiting zone
  if (rateLimit) {
    config += `# Rate limiting
limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=addr:10m;
\n`;
  }

  // Upstream block for reverse proxy
  if (type === 'reverse-proxy' || type === 'load-balancer') {
    config += `upstream backend {
    server ${upstream};
    keepalive 32;
}
\n`;
  }

  // Main server block
  config += `server {
    listen 80;
    server_name ${domain} www.${domain};

    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}
\n`;

  // HTTPS server block
  config += `server {
    listen 443 ssl http2;
    server_name ${domain} www.${domain};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/${domain}/chain.pem;

    # Modern SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
`;

  // HSTS header (only if SSL)
  if (ssl) {
    config += `    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
`;
  }

  // Gzip compression
  if (gzip) {
    config += `
    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
`;
  }

  // Rate limiting
  if (rateLimit) {
    config += `
    # Rate Limiting
    limit_req zone=api burst=20 nodelay;
    limit_conn addr 10;
`;
  }

  // Configuration based on type
  if (type === 'static') {
    config += `
    # Static Site Configuration
    root /var/www/${domain};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
`;
  } else if (type === 'reverse-proxy') {
    config += `
    # Reverse Proxy Configuration
    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
    }
`;
  } else if (type === 'api') {
    config += `
    # API Configuration
    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS headers
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range" always;
    }

    # Health check endpoint (no rate limit)
    location /health {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        access_log off;
    }
`;
  }

  // Caching configuration
  if (caching) {
    config += `
    # Proxy caching
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=24h max_size=100m;

    location / {
        proxy_cache STATIC;
        proxy_cache_valid 200 1d;
        proxy_cache_use_stale error timeout invalid_header updating;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
    }
`;
  }

  // Logging configuration
  config += `
    # Logging
    access_log /var/log/nginx/${domain}.access.log;
    error_log /var/log/nginx/${domain}.error.log;
}
`;

  return config;
}
